Find the SVD of $A$, $UΣV^T$
, where $A =\begin{pmatrix}
3 &2  &2 \\ 
 2&3  &-2 
\end{pmatrix}$

In [1]:
import numpy as np
from scipy import linalg
import sympy as sp

In [2]:
A= np.array([[3,2,2],
             [2,3,-2]])
AAT=A@A.T
ATA=A.T@A
AAT,ATA

(array([[17,  8],
        [ 8, 17]]),
 array([[13, 12,  2],
        [12, 13, -2],
        [ 2, -2,  8]]))

In [3]:
a,b = np.linalg.eig(AAT) 
a,b

(array([25.,  9.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [6]:
ATA

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

In [4]:
np.linalg.eig(ATA)

(array([2.50000000e+01, 3.52669283e-15, 9.00000000e+00]),
 array([[-7.07106781e-01, -6.66666667e-01,  2.35702260e-01],
        [-7.07106781e-01,  6.66666667e-01, -2.35702260e-01],
        [-4.33680869e-17,  3.33333333e-01,  9.42809042e-01]]))

In [7]:
U,S,V=linalg.svd(A)
U,S,V

(array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[ 7.07106781e-01,  7.07106781e-01,  3.88578059e-16],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [22]:
U@linalg.diagsvd(S,2,3)@V

array([[ 3.,  2.,  2.],
       [ 2.,  3., -2.]])

In [ ]:
from sympy.abc import x,y,z
A=sp.Matrix([[-12*x,12*y,2*z],
             [12*x,-12*y,-2*z],
             [2*x,]])