In [2]:
import numpy as np
from scipy import linalg

In [2]:
toan=np.array([0,0,0,0,10,10,0,0,0,0])

In [3]:
toan.mean()

2.0

In [4]:
toan.std()

4.0

In [5]:
toan.var()

16.0

In [51]:
M1 = np.array([[12,4,3],[5,5,3],[1,5,15]])
M1

array([[12,  4,  3],
       [ 5,  5,  3],
       [ 1,  5, 15]])

In [52]:
M2 = np.matrix([[12,4,2],[5,3,6]])
M2

matrix([[12,  4,  2],
        [ 5,  3,  6]])

In [53]:
M2.dot(M1)

matrix([[166,  78,  78],
        [ 81,  65, 114]])

In [11]:
a=np.reshape(np.arange(36.0),(6,6))

In [12]:
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [17]:
b=a.resize([6,6])

In [22]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
b=np.identity(6)

In [24]:
b

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
a.dot(b)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [26]:
b.dot(a)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [27]:
a.dot(a)

array([[ 330,  345,  360,  375,  390,  405],
       [ 870,  921,  972, 1023, 1074, 1125],
       [1410, 1497, 1584, 1671, 1758, 1845],
       [1950, 2073, 2196, 2319, 2442, 2565],
       [2490, 2649, 2808, 2967, 3126, 3285],
       [3030, 3225, 3420, 3615, 3810, 4005]])

In [13]:
b=np.asmatrix(a)

In [16]:
np.linalg.inv(b)

LinAlgError: Singular matrix

In [17]:
np.linalg.det(a)

0.0

In [30]:
a.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [ ]:
np.linalg.

In [ ]:
linalg.