# Giới thiệu python và numpy

## 1. List

In [1]:
danhsach1=[1.,3.]

In [2]:
danhsach2=[5.,7.]

In [5]:
danhsach=danhsach1+danhsach2

In [7]:
danhsach_gapdoi = 2 * danhsach
print(danhsach_gapdoi)

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


In [8]:
danhsach*2

[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]

In [9]:
danhsach/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
anh_xa

In [11]:
tap_hop = set(anh_xa)
tap_hop

{(1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8)}

In [20]:
lay_TT, lay_monhoc , lay_diem = zip(*anh_xa)


In [21]:
import itertools
tap_sinh = list (itertools.chain (range (4), range (5,10), range (15, 20) ))
tap_sinh

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]

In [22]:
list(zip(range(4), range(7, 12), reversed(range(11) ) ) )


[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [23]:
import math

In [24]:
math.inf

inf

In [25]:
type(math.inf)

float

In [26]:
x = 1
math.expm1(x) == math.exp(x) - 1

True

In [29]:
x=1e-5
print(math.expm1(x))
print(math.exp(x)-1)
math.expm1(x) == math.exp(x) - 1

1.0000050000166667e-05
1.0000050000069649e-05


False

## 2.Làm quen với numpy

In [31]:
import numpy as np

In [32]:
vec1=np.array([1.,3.,5.])
vec1*2

array([ 2.,  6., 10.])

In [35]:
a=[1.,3.,5]
a*2

[1.0, 3.0, 5, 1.0, 3.0, 5]

In [36]:
vec1*vec1

array([ 1.,  9., 25.])

In [37]:
vec1/2

array([0.5, 1.5, 2.5])

In [38]:
vec1+vec1

array([ 2.,  6., 10.])

In [41]:
vec2 = np.array([2.,4.])
vec1+vec2

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [44]:
vec3=np.array([2,4,6],dtype=float)
vec1 + vec3

array([ 3.,  7., 11.])

In [45]:
vec1/vec3

array([0.5       , 0.75      , 0.83333333])

In [46]:
vec1*vec3

array([ 2., 12., 30.])

In [47]:
2* vec1+ 5*vec3

array([12., 26., 40.])

In [48]:
vec3[2]

6.0

In [50]:
vec4=np.linspace(0,20,5)
vec4

array([ 0.,  5., 10., 15., 20.])

In [58]:
vec36=np.linspace(0,36,10)

In [59]:
vec36

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.])

In [67]:
vec5=np.zeros(5)
vec5

array([0., 0., 0., 0., 0.])

In [69]:
vec6=np.ones(5)
vec6

array([1., 1., 1., 1., 1.])

In [80]:
vec7=np.empty(5)
vec7

array([1., 1., 1., 1., 1.])

In [81]:
np.random.random(5)

array([0.22286523, 0.1872596 , 0.73387536, 0.79563806, 0.47272866])

In [88]:
np.random.randint(0,7,size=(5,3))

array([[6, 4, 1],
       [3, 1, 0],
       [3, 2, 1],
       [0, 0, 5],
       [2, 1, 3]])

In [90]:
v=np.array([1,3,5],dtype=float)
v

array([1., 3., 5.])

In [91]:
np.sum(v)

9.0

In [92]:
v.shape

(3,)

In [93]:
v.T

array([1., 3., 5.])

In [94]:
v.transpose()

array([1., 3., 5.])

In [95]:
v1=v[:2]
v1

array([1., 3.])

In [96]:
v[0]=5
v

array([5., 3., 5.])

In [97]:
v1

array([5., 3.])

In [101]:
v1[:2] = [1.,2.,3.]

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [103]:
v1[:2]=[1.,2.]
v1

array([1., 2.])

In [104]:
v3 = 2*v[:2]+v1*3
v3

array([ 5., 10.])

In [105]:
v1=[4,6]

In [106]:
v3

array([ 5., 10.])

In [107]:
v

array([1., 2., 5.])

In [108]:
v+10.0

array([11., 12., 15.])

In [109]:
np.sqrt(v)

array([1.        , 1.41421356, 2.23606798])

In [110]:
np.cos(v)

array([ 0.54030231, -0.41614684,  0.28366219])

In [111]:
np.sin(v)

array([ 0.84147098,  0.90929743, -0.95892427])

In [114]:
np.sin(1)

0.8414709848078965

In [120]:
print(v1)
print(v3)

[4, 6]
[ 5. 10.]


In [115]:
np.dot(v1, v3)

80.0

In [121]:
v1=np.array([4,6],dtype= float)

In [122]:
v1.dot(v3)

80.0

In [123]:
v3.dot(v1)

80.0

In [124]:
v

array([1., 2., 5.])

In [125]:
np.linalg.norm(v)

5.477225575051661

In [126]:
len(v)

3

In [130]:
v3=np.array([3,5],dtype=float)

In [131]:
np.hstack([v,v3])

array([1., 2., 5., 3., 5.])

In [132]:
np.vstack([v1,v3])

array([[4., 6.],
       [3., 5.]])

In [137]:
def symp(v):
    n = len(v) // 2
    return np.hstack([-v[n:], v[:n]])

In [138]:
v6 = np.array([1., 3., 5., 7., 9., 11.])
v7 = symp(v6)
v7

array([ -7.,  -9., -11.,   1.,   3.,   5.])

### 3.2 thể hiện ma trận với np

In [140]:
M1 = np.array([[9,12],
               [23,30]])
M1

array([[ 9, 12],
       [23, 30]])

In [141]:
u = np.array([2,1])

In [142]:
tichM1_u=M1.dot(u)
tichM1_u

array([30, 76])

In [145]:
u.dot(M1)

array([41, 54])

In [148]:
np.dot(M1,u)

array([30, 76])

In [151]:
mat8=np.empty([4,5])
mat8


array([[0.00000000e+000, 1.58101007e-322, 0.00000000e+000,
        0.00000000e+000,             nan],
       [4.94065646e-324, 7.76671195e-321, 3.95252517e-323,
        1.12740484e-311, 1.12740484e-311],
       [0.00000000e+000, 0.00000000e+000, 1.12740484e-311,
        7.76671195e-321, 4.94065646e-324],
       [1.12740340e-311, 7.76671195e-321, 1.12741793e-311,
        1.23516411e-322, 2.12199579e-314]])

## Sympy

In [152]:
import sympy as sp

In [154]:
M = sp.Matrix([[1,3],[2,4]])
M

Matrix([
[1, 3],
[2, 4]])

In [157]:
M.det()

-2

In [161]:
v1 = sp.Matrix([[5,7]])
v2=v1.T

In [162]:
M.dot(v2)

[26, 38]

In [170]:
M.dot(v1)

[26, 38]