# BÀI 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR,TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR RIÊNG

### 1.2. Tích vô hướng, trực giao và ứng dụng


In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng
print (tich)


32


In [2]:
np.dot(a,b),np.dot(b,a)

(32, 32)

#### Độ dài/chuẩn của vector:

Chuẩn 2: ‖𝑢‖ = $\sqrt{< 𝑢, 𝑢 >}$ (thường được sử dụng, nếu không đề cập thêm thì kí hiệu ‖𝑢‖
là chuẩn 2)

In [3]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a,2)

3.7416573867739413

In [4]:
#Chuẩn 1: ‖𝑢‖1 = ∑|𝑢
a = np.array([1,2,-3])
np.linalg.norm(a,3)

3.3019272488946263

In [5]:
def chuan(v,k):
    tong = 0
    for i in range (len(v)):
             tong = tong + abs (v[i]**k)
    ketqua = math.pow(tong, 1.0/k) # <- lay can bac k cua tong
    return ketqua

In [6]:
import math
a = np.array([1,2,-3])
chuan(a, 1)


6.0

In [7]:
 np.linalg.norm(a,1)

6.0

In [8]:
chuan(a, 2)

3.7416573867739413

In [9]:
 np.linalg.norm(a,2)

3.7416573867739413

In [10]:
chuan(a, 3)

3.3019272488946263

In [11]:
 np.linalg.norm(a,3)

3.3019272488946263

In [12]:
chuan(a, 1000)

1.0206361019360273

In [13]:
np.linalg.norm(a,1000)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py:2568: RuntimeWarning: overflow encountered in power
  absx **= ord


inf

### 2. Tổ hợp tuyến tính

Bài toán Thiết kế ô tô hoặc chất hàng vào container/tàu thủy

In [14]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1]) 
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [15]:
v = (1.0/m)*MT.dot(mi)
v

array([1.3, 0.9, 0. ])

In [16]:
print('vậy trọng tâm của các điểm là v=',v)

vậy trọng tâm của các điểm là v= [1.3 0.9 0. ]


 #### 3. Trị riêng, vector riêng của ma trận và ứng dụng

In [17]:
A = np.array([[0.998,0.136],
              [0.002,0.864]])
v = np.array([0.95,0.05])
A_100 = np.linalg.matrix_power(A,100)
A_100

array([[0.98550725, 0.9855069 ],
       [0.01449275, 0.0144931 ]])

In [18]:
ans=A_100 @ v
ans

array([0.98550723, 0.01449277])

#### Trạng thái cân bằng (Markov)

In [19]:
from scipy import linalg
A= np.array([[1,-68],[1,1]])
v= np.array([0,1])
linalg.solve(A,v)

array([0.98550725, 0.01449275])

In [24]:
# thử nghiệm vs sympy 
import sympy as sym
x,y = sym.symbols('x,y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1,-68],[1,1]])
v = sym.Matrix([0,1])
ans = sym.solve([A*xy-v])
print(sym.pretty(ans))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


#### Trị riêng và vector riêng của ma trận

In [57]:
A = np.array([[1,6],[5,2]])
u= np.array([6,-5])
ans1=A@u

In [34]:
ans2=-4*u

In [35]:
(ans1==ans2).all()

True

In [36]:
np.equal(ans1,ans2)

array([ True,  True])

In [58]:
linalg.eigvals(A)

array([-4.+0.j,  7.+0.j])

* Quy trình tính toán trị riêng của ma trận : $det(A - \lambda I)=0$

In [43]:
x,y,Lambda = sym.symbols('x y Lambda')
I = sym.eye(2)
A = sym.Matrix([[2,3],[3,-6]])
pt = sym.Eq(sym.det(Lambda*I-A),0)
ans = sym.solve(pt)
print([sym.N(phantu,4)for phantu in ans])

[-7.000, 3.000]


In [45]:
print(sym.pretty(ans))

[-7, 3]


* Quy trình tính toán vector riêng của ma trận: $(A-\lambda I)x=0$

In [49]:
x1,x2=sym.symbols('x1 x2')
X = sym.Matrix([x1,x2])
X

Matrix([
[x1],
[x2]])

In [53]:
vector=(A-3*I)*X
vector

Matrix([
[ -x1 + 3*x2],
[3*x1 - 9*x2]])

In [56]:
ans=sym.solve(vector)
sym.pretty(ans)

'{x₁: 3⋅x₂}'

#### 3.3.Ứng dụng cua trị riêng và vector riêng

In [59]:
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1./3,3],[1,1]])
P1 = np.linalg.inv(P)
P1

array([[-0.3,  0.9],
       [ 0.3,  0.1]])

In [60]:
A@P

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [61]:
P@D

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

### Câu hỏi bổ sung

### Câu 1

In [63]:
a = np.array([1,2,3])
linalg.norm(a)

3.7416573867739413

In [64]:
np.sqrt(a@a)

3.7416573867739413

In [65]:
np.sqrt(np.inner(a,a))

3.7416573867739413

In [66]:
mag = lambda x: math.sqrt(sum(i**2 for i in x))

In [68]:
mag(a)

3.7416573867739413

### Câu 2 