# BÀI 8: KHÔNG GIAN VECTOR VÀ ÁNH XẠ TUYẾN TÍNH (PHẦN 2)

## 1. Kiểm lý thuyết về ánh xạ tuyến tính
### 1.1.Kiểm tra một ánh xạ là ánh xạ tuyến tính

In [1]:
import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c') # khai báo thêm 3 biến a, b, c giả định X = (a, b, c)
d, e, f = sp.symbols('d e f') # khai báo thêm 3 biến d, e, f giả định Y = (e, d, f)
f1(a, b, c)

a - b + c

In [2]:
f1(d, e, f)


d - e + f

In [3]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [6]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [5]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [3]:
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())

True

In [5]:
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

True

### 1.2.Tìm tổ hợp tuyến tính cho một ánh xạ tuyến tính

Để tìm tổ hợp tuyến tính để tính ánh xạ tuyến tính với các giá trị có sẵn, chúng ta giải phương trình 
để tìm ra các hệ số của tổ hợp tuyến tính, sau đó chúng ta tính ánh xạ tuyến tính đó

Ví dụ: Cho $𝑓:$ $ℝ^2 → ℝ^3$
có cơ sở của $ℝ^2$
là $𝐵 =$ {$𝑢1 = (1,2); 𝑢2 = (3,5)$} và $𝑓(𝑢1
) = (1,1,2)$, 
$𝑓(𝑢2
) = (4,2,1).$ Tìm $𝑓(𝑢3
) = 𝑓(4,5)$

Tìm tổ hợp tuyến tính: 𝑢3 = 𝛼𝑢1 + 𝛽𝑢2, nghĩa là giải ra 𝛼 và 𝛽 

In [2]:
from scipy import linalg
import numpy as np
a,b=sp.symbols('a b')
u=np.array([[1,3],[2,5]])
x=np.array([4,5])
ans=linalg.solve(u,x)
ans

array([-5.,  3.])

Sau đó, chúng ta tính toán theo công thức 𝑓(𝑢3
) = 𝛼𝑓(𝑢1
) + 𝛽𝑓(𝑢2). 

In [19]:
fu1=np.array([1,1,2])
fu2=np.array([4,2,1])
answer = ans[0]*fu1+ans[1]*fu2
answer

array([ 7.,  1., -7.])

### 1.3.Tìm ánh xạ tuyến tính

Để tìm ánh xạ tuyến tính với các giá trị có sẵn, chúng ta giải phương trình để tìm ra các hệ số của ánh xạ.

Ví dụ: Tương tự như trên, chúng ta hãy tìm ánh xạ tuyến tính của f khi biết  $𝑓: ℝ^2 \rightarrow ℝ^3$
có cơ sở của $ℝ^2$ là<br> $𝐵 =$ {$𝑢1 = (1,2); 𝑢2 = (3,5)$} và $𝑓(𝑢1) = (1,1,2), 𝑓(𝑢2
) = (4,2,1).$

Giải hệ với 𝑢 = (𝑥, 𝑦) bất kỳ để tìm ra $\alpha$ và $\beta$

In [21]:
import sympy as sp 
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])

{a: -5*x + 3*y, b: 2*x - y}

Từ công thức $𝑢 = 𝛼𝑢1 + 𝛽𝑢2$, thay thế vào công thức $𝑓(𝑢) = 𝛼𝑓(𝑢1) + 𝛽𝑓(𝑢2)$ để tìm được ánh xạ
tuyến tính.

In [25]:
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
fu

array([a + 4*b, a + 2*b, 2*a + b], dtype=object)

In [26]:
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
fu

array([3*x - y, -x + y, -8*x + 5*y], dtype=object)

 ### 1.4.Tìm nhân của ánh xạ tuyến tính


Theo định nghĩa, $𝐾𝑒𝑟(𝑓) =$ {$𝑥 ∈ 𝑉|𝑓(𝑥) = 0$}. Như vậy, tìm $Ker(f)$ là giải phương trình $𝑓(𝑥) = 0.$

Ví dụ: Cho ánh xạ $𝑓$ từ $ℝ^3 \rightarrow ℝ^3$<br>
$$𝑓(𝑥1, 𝑥2, 𝑥3) = (𝑥1 + 𝑥2 − 𝑥3; 2𝑥1 + 3𝑥2 − 𝑥3, 3𝑥1 + 5𝑥2 − 𝑥3)$$

In [27]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3,2*x1+3*x2-x3,3*x1+5*x2-x3],[x1,x2,x3])

{x1: 2*x3, x2: -x3}

#### 1.5.Tìm ảnh của ánh xạ tuyến tính

In [30]:
x1, x2, x3 = sp.symbols('x1 x2 x3')
y1, y2, y3 = sp.symbols('y1 y2 y3')
sp.solve([x1+x2-x3-y1,2*x1+3*x2-x3-y2,3*x1+5*x2-x3-y3],[x1,x2,x3])

[]

#### 1.6. Ma trận của ánh xạ tuyến tính trong cặp cơ sở

Ví dụ: Cho ánh xạ f từ $R^2 → R^2: f(x, y) = (x − y, x) $<br>
Với 2 cơ sở $B = ${$u1 = (−1; 1), u2 = (1; 0)$} và $F=$ {$v1 = (1; 2), v2 = (1; 3)$}.<br>
tìm Ma trận $A = [f]_B^F$
được xác định như sau:

B1: Tính các $f(u_i)$

In [4]:
def fxy(x,y):
    return np.array([x-y,x])
fu1 = fxy(-1,1)
fu2 = fxy(1,0)
fu1,fu2

(array([-2, -1]), array([1, 1]))

B2: Bước 2: Xác định các giá trị $[f(u_i)]_F$

$[f(ui)]F = [a_i b_i].T \leftrightarrow f(u_i) = a_iv_1 + b_iv_2 + ... + n_iv_n$

In [5]:
a1,a2,b1,b2 = sp.symbols('a1 a2 b1 b2')
fu1f = sp.solve([a1+b1+2, 2*a1+3*b1+1],[a1,b1])
fu1f

{a1: -5, b1: 3}

In [10]:
fu2f = sp.solve([a1+b1-1, 2*a1+3*b1-1],[a1,b1])
fu2f

{a1: 2, b1: -1}

B3 trả về ma trận bằng cách dựng đứng 2 vector vừa tìm được 

In [13]:
A = sp.Matrix([[-5,3],[2,-1]])
A.T

Matrix([
[-5,  2],
[ 3, -1]])

In [82]:
import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[5,5],
                [-1,7]]) # cos(pi/4)

LA.orth(B)

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [3]:
A=np.random.randint(-10,10,size=(2,3))
A

array([[  6,  -5,   5],
       [  0, -10,  -7]])

In [5]:
linalg.qr(A)

(array([[ 1.,  0.],
        [-0.,  1.]]),
 array([[  6.,  -5.,   5.],
        [  0., -10.,  -7.]]))

### 3. [Tham khảo] Ứng dụng 2 – Xếp hạng các trang web với trị riêng và vector riêng

In [8]:
A = np.array([[0,0,1.0/2, 1.0/2],
    [1.0/3,0,0,0],
    [1.0/3,0,0,1.0/2],
    [1.0/3,1.0,1.0/2,0]])
x = np.array([1,1,1,1])

In [9]:
A@x

array([1.        , 0.33333333, 0.83333333, 1.83333333])

In [14]:
x = np.array([1.0, 1.0, 1.0, 1.0])
print(0,x)
for i in range(10):
    x = np.dot(A, x)
    print (i+1, x)

0 [1. 1. 1. 1.]
1 [1.         0.33333333 0.83333333 1.83333333]
2 [1.33333333 0.33333333 1.25       1.08333333]
3 [1.16666667 0.44444444 0.98611111 1.40277778]
4 [1.19444444 0.38888889 1.09027778 1.32638889]
5 [1.20833333 0.39814815 1.06134259 1.33217593]
6 [1.19675926 0.40277778 1.06886574 1.33159722]
7 [1.20023148 0.39891975 1.06471836 1.3361304 ]
8 [1.20042438 0.40007716 1.06814236 1.3313561 ]
9 [1.19974923 0.40014146 1.06581951 1.3342898 ]
10 [1.20005466 0.39991641 1.06706131 1.33296762]


#### 3.2.Xử lý dangling node trong thuật toán Pagerank

In [16]:
A = np.array([[0,0,1.0/2, 0.0],
            [1.0/3,0,0,0],
            [1.0/3,0,0,0.0],
            [1.0/3,1.0,1.0/2,0]])
x = np.array([1,1,1,1])
for i in range(5):
    x = np.dot(A, x)
    print (i+1, x)

1 [0.5        0.33333333 0.33333333 1.83333333]
2 [0.16666667 0.16666667 0.16666667 0.66666667]
3 [0.08333333 0.05555556 0.05555556 0.30555556]
4 [0.02777778 0.02777778 0.02777778 0.11111111]
5 [0.01388889 0.00925926 0.00925926 0.05092593]


In [17]:
x = np.array([1.0, 1.0, 1.0, 1.0])
A = np.array([[0,0,1.0/2, 1/4.0],
            [1.0/3,0,0,1/4.0],
            [1.0/3,0,0,1/4.0],
            [1.0/3,1.0,1.0/2,1/4.0]])

for i in range(7):
    x = np.dot(A, x)
    print (i+1, x)

1 [0.75       0.58333333 0.58333333 2.08333333]
2 [0.8125     0.77083333 0.77083333 1.64583333]
3 [0.796875   0.68229167 0.68229167 1.83854167]
4 [0.80078125 0.72526042 0.72526042 1.74869792]
5 [0.79980469 0.70410156 0.70410156 1.79199219]
6 [0.80004883 0.71459961 0.71459961 1.77075195]
7 [0.79998779 0.70937093 0.70937093 1.78127035]


In [18]:
np.max(x)

1.781270345052083

#### 3.3.Xử lý nhánh web reducible còn gọi là các thành phần không kết nối hoặc thành phần không liên thông (disconnected components)

In [19]:
A = np.array([[0.0, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1.0/3, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1/3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1.0/3,1/2.0,1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [0.0 ,1/2.0, 0.0, 0.0, 0.0,1/2.0, 0.0,0.0],
            [0.0, 0.0, 0.0,0.0, 0.0, 0.0, 1.0,1/2.0],
            [0.0, 0.0, 0.0,1/2.0, 1.0, 0.0, 0.0, 1/2.0],
            [0.0, 0.0, 0.0,0.0, 0.0,1/2.0, 0.0, 0.0]])

N = 8
x = np.array([1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N])
for i in range(7):
    x = np.dot(A, x)
    print (i+1, x)

1 [0.0625     0.10416667 0.04166667 0.16666667 0.125      0.1875
 0.25       0.0625    ]
2 [0.02083333 0.04166667 0.02083333 0.09375    0.14583333 0.28125
 0.23958333 0.09375   ]
3 [0.01041667 0.01736111 0.00694444 0.03819444 0.16145833 0.28645833
 0.23958333 0.140625  ]
4 [0.00347222 0.00694444 0.00347222 0.015625   0.15190972 0.30989583
 0.25086806 0.14322917]
5 [0.00173611 0.00289352 0.00115741 0.00636574 0.15842014 0.32248264
 0.23133681 0.15494792]
6 [0.0005787  0.00115741 0.0005787  0.00260417 0.16268808 0.30881076
 0.23907697 0.16124132]
7 [2.89351852e-04 4.82253086e-04 1.92901235e-04 1.06095679e-03
 1.54984086e-01 3.19697627e-01 2.44610822e-01 1.54405382e-01]


In [22]:
d = 0.85
N = 8
x = np.array([1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N, 1.0/N])
A = np.array([[0.0, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1.0/3, 0.0, 1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1/3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [1.0/3,1/2.0,1/2.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [0.0 ,1/2.0, 0.0, 0.0, 0.0,1/2.0, 0.0,0.0],
            [0.0, 0.0, 0.0,0.0, 0.0, 0.0, 1.0,1/2.0],
            [0.0, 0.0, 0.0,1/2.0, 1.0, 0.0, 0.0, 1/2.0],
            [0.0, 0.0, 0.0,0.0, 0.0,1/2.0, 0.0, 0.0]])
M = d*A + ((1-d)/N)* np.ones([N,N])

for i in range(7):
    x= np.dot(M,x)
    print(i+1,x)

1 [0.071875   0.10729167 0.05416667 0.16041667 0.125      0.178125
 0.23125    0.071875  ]
2 [0.04177083 0.06213542 0.03911458 0.10773437 0.14005208 0.24585938
 0.22372396 0.09445312]
3 [0.03452702 0.04636209 0.02973839 0.07276964 0.14880111 0.24821126
 0.22287728 0.12239355]
4 [0.02999532 0.03977798 0.02713916 0.05948186 0.14255018 0.25881945
 0.2267818  0.12284629]
5 [0.02854774 0.03704642 0.02551228 0.05395206 0.14391751 0.26198781
 0.21567072 0.12701187]
6 [0.02759859 0.03568711 0.0248444  0.05143184 0.14384542 0.25405603
 0.21599542 0.12810069]
7 [0.02708811 0.03490771 0.02434884 0.05007473 0.13967008 0.25456814
 0.21509917 0.12450305]
