# <center>Giải hệ phương trình tuyến tính và thuật giải Gauss</center> 

## Giải hệ phương trình tuyến tính

### Giải hệ Cramer

Ví dụ: Giải hệ phương trình:
$$2x−y−z=4$$
$$3x+4y−2z=11$$
$$3x−2y+4z=11$$

### Dùng phương trình ma trận để tìm X:
$$AX = b \Leftrightarrow X=A^{−1} b$$

In [1]:
import numpy as np
import math
from scipy.linalg import lu

A = np.array([[2, -1, -1], # Ma trận A
             [3, 4, -2],
             [3, -2, 4]])
b = np.array([4, 11, 11]).reshape(-1, 1) # Ma trận b
x = np.linalg.inv(A) @ b # Ma trận x tính bằng công thức x = A^(−1) b
print(x) # Kết quả nghiệm X
b

[[3.]
 [1.]
 [1.]]


array([[ 4],
       [11],
       [11]])

Vậy, nghiệm của hệ phương trình: $$x_1=3; x_2=1; x_3=1$$

### Dùng định thức:
Nghiệm của hệ Cramer có dạng: $$x_{j}=\frac{det(A_{j})}{det(A)}$$
<br>$$2x−y−z=4$$
$$3x+4y−2z=11$$
$$3x−2y+4z=11$$

In [10]:
A = np.array([[2, -1, -1], # Ma trận A
             [3, 4, -2],
             [3, -2, 4]])
b = np.array([4, 11, 11]).reshape(-1, 1) # Ma trận b

A1 = np.hstack((b, A[:, 1:])) # Ma trận A1
A2 = np.hstack((A[:, :1], b, A[:, 2:])) # Ma trận A2
A3 = np.hstack((A[:, :2], b)) # Ma trận A3
print(A1),print(A2),print(A3)

print('x1 = ', np.linalg.det(A1) / np.linalg.det(A))
print('x2 = ', np.linalg.det(A2) / np.linalg.det(A))
print('x3 = ', np.linalg.det(A3) / np.linalg.det(A))

[[ 4 -1 -1]
 [11  4 -2]
 [11 -2  4]]
[[ 2  4 -1]
 [ 3 11 -2]
 [ 3 11  4]]
[[ 2 -1  4]
 [ 3  4 11]
 [ 3 -2 11]]
x1 =  2.9999999999999982
x2 =  1.0000000000000009
x3 =  1.0


In [8]:
b

array([[ 4],
       [11],
       [11]])

Vậy, nghiệm của hệ phương trình: $$x_1=3; x_2=1; x_3=1$$

## Thuật giải Gauss <a class="anchor" id="c1"></a>

###  Các bước thực hiện:
* Viết ma trận mở rộng.
* Sử dụng các phép biến đổi sơ cấp trên dòng để biến ma trận này về dạng ma trận bậc thang.
* Xét xem hệ này rơi vào trường hợp nào (vô nghiệm, vô số nghiệm, nghiệm duy nhất).
* Lập hệ phương trình tương ứng với ma trận bậc thang vừa tìm được.
* Giải hệ ngược từ dưới lên trên.

In [3]:
def Gaussian_elimination(matrix): # Khai báo hàm thực hiện khử Gauss
    zero_pos = []
    for i in range(0, len(matrix)): # Tìm số lượng chữ số '0' từ trái sang phải của từng dòng
        tmp_arr = []
        if matrix[i][0] == 0:
            tmp_arr.append(0)
            j = 1
            while j < len(matrix[i]) and matrix[i][j] == 0:
                tmp_arr.append(j)
                j += 1
            zero_pos.append(len(tmp_arr))
        else:
            zero_pos.append(0)   

    for i in range(0, len(matrix)):             # Các dòng được sắp xếp theo thứ tự: dòng nào có số lượng chữ số '0' từ trái sang phải
        for j in range(i + 1, len(matrix)):     # nhiều nhất sẽ là dòng nằm cuối cùng của ma trận, giảm dần từ dưới lên trên
            if zero_pos[i] > zero_pos[j]:       
                matrix[i], matrix[j] = matrix[j], matrix[i]
                zero_pos[i], zero_pos[j] = zero_pos[j], zero_pos[i]

    for i in range(1, len(matrix)):
        if zero_pos[i] > zero_pos[i - 1]:  # Dòng hiện tại phải có số lượng chữ số '0' từ trái sang phải lớn hơn dòng trước đó
            continue                      
        else: # Khử Gauss                            
            for j in range(zero_pos[i], i):         
                k = matrix[i][j] / matrix[j][j]
                row = []
                for m in matrix[j]:
                    row.append(m * k)
                for n in range(0, len(matrix[i])):
                    matrix[i][n] -= row[n]

### Ví dụ 1: Giải hệ phương trình:
$$x_{1}+x_{2}+2x_{3}+3x_{4}=1$$
$$3x_{1}-x_{2}-x_{3}-2x_{4}=-4$$
$$2x_{1}+3x_{2}-x_{3}-x_{4}=-6$$
$$x_{1}+2x_{2}+3x_{3}-x_{4}=-4$$

In [4]:
A = np.array([[1, 1, 2, 3], # Ma trận A
             [3, -1, -1, -2],
             [2, 3, -1, -1],
             [1, 2, 3, -1]])
b = np.array([1, -4, -6, -4]).reshape(-1, 1) # Ma trận b

A_comma = np.hstack((A, b))

Gaussian_elimination(A_comma)
A_comma

array([[  1,   1,   2,   3,   1],
       [  0,  -4,  -7, -11,  -7],
       [  0,   0,  -6,  -9,  -9],
       [  0,   0,   0,  -6,  -6]])

Ta có: rank(𝐴) = rank(𝐴’) = 4 nên hệ phương trình có nghiệm duy nhất.

Từ ma trận trên, ta lập được hệ phương trình tương ứng:
$$x_{1}+x_{2}+2x_{3}+3x_{4}=1$$
$$4x_{2}+7x_{3}+11x_{4}=7$$
$$6x_{3}+9x_{4}=9$$
$$6x_{4}=6$$
Vậy nghiệm của hệ phương trình là:
$$x_{1}=-1$$
$$x_{2}=-1$$
$$x_{3}=0$$
$$x_{4}=1$$

### Ví dụ 2: Giải hệ phương trình:
$$x+y-z=0$$
$$2x+3y+z=1$$
$$3x+y-9z=2$$

In [5]:
A = np.array([[1, 1, -1], # Ma trận A
             [2, 3, 1],
             [3, 1, -9]])
b = np.array([0, 1, 2]).reshape(-1, 1) # Ma trận b

A_comma = np.hstack((A, b))

Gaussian_elimination(A_comma)
A_comma

array([[ 1,  1, -1,  0],
       [ 0,  1,  3,  1],
       [ 0,  0,  0,  4]])

Ta có rank(𝐴) = 2 < rank(𝐴’) = 3 nên hệ phương trình vô nghiệm

### Ví dụ 3: Giải hệ phương trình:
$$x+y-3z=1$$
$$2x+y-5z=1$$
$$x-3y+z=-3$$

In [6]:
A = np.array([[1, 1, -3], # Ma trận A
             [2, 1, -5],
             [1, -3, 1]])
b = np.array([1, 1, -3]).reshape(-1, 1) # Ma trận b

A_comma = np.hstack((A, b))

Gaussian_elimination(A_comma)
A_comma

array([[ 1,  1, -3,  1],
       [ 0, -1,  1, -1],
       [ 0,  0,  0,  0]])

Ta có rank(𝐴) = rank(𝐴′) = 2 < 3 nên hệ phương trình có vô số nghiệm phụ thuộc vào 3 – 2 = 1 tham số.

Từ ma trận trên, ta lập được hệ phương trình tương ứng:
$$x+y-3z=1$$
$$y-z=1$$
Vậy nghiệm của hệ phương trình là:
$$x=2\alpha$$
$$y=1+\alpha$$
$$z=\alpha, \alpha\in\mathbb{R}$$