In [2]:
import numpy as np
import math


In [72]:
#bài 1
matA = np.array([[7,8,9,5],
            [8,7,4,6],
            [7,5,8,6],
            [6,8,5,4],
            [9,9,8,7],
            [10,8,9,8]])
print(matA)
A=(matA[0,0]*10+matA[0,1]*20+matA[0,2]*30+matA[0,3]*40)/100
B=(matA[1,0]*10+matA[1,1]*20+matA[1,2]*30+matA[1,3]*40)/100
C=(matA[2,0]*10+matA[2,1]*20+matA[2,2]*30+matA[2,3]*40)/100
D=(matA[3,0]*10+matA[3,1]*20+matA[3,2]*30+matA[3,3]*40)/100
E=(matA[4,0]*10+matA[4,1]*20+matA[4,2]*30+matA[4,3]*40)/100
F=(matA[5,0]*10+matA[5,1]*20+matA[5,2]*30+matA[5,3]*40)/100
dict_score={"A":A,"B":B,"C":C,"D":D,"E":E,"F":F}
for k,v in dict_score.items():
    if (v>=5 ):
        p='pass'
    else:
        p=''
    print('Name: '+ k +'| Mean: '+ str(v)+'  '+p)


[[ 7  8  9  5]
 [ 8  7  4  6]
 [ 7  5  8  6]
 [ 6  8  5  4]
 [ 9  9  8  7]
 [10  8  9  8]]
Name: A| Mean: 7.0  pass
Name: B| Mean: 5.8  pass
Name: C| Mean: 6.5  pass
Name: D| Mean: 5.3  pass
Name: E| Mean: 7.9  pass
Name: F| Mean: 8.5  pass


In [75]:
tile=np.array([[0.1,0.2,0.3,0.4]]).transpose()
ketqua=matA.dot(tile)
ketqua

array([[7. ],
       [5.8],
       [6.5],
       [5.3],
       [7.9],
       [8.5]])

In [76]:
#bài 2
mat1=np.random.randint(10,size =(3,3))
mat2=np.random.randint(10,size = (3,3))
print(mat1)
print(mat2)

[[5 7 8]
 [2 0 0]
 [7 7 4]]
[[0 9 0]
 [9 9 7]
 [2 6 9]]


In [77]:
print('Tổng phần tử của 2 ma trân là :')
print(mat1.sum())
print(mat2.sum())

Tổng phần tử của 2 ma trân là :
40
51


In [82]:
print('norm của 2 ma trận là :')
print(round(np.linalg.norm(mat1[0]),2))
print(round(np.linalg.norm(mat2[2]),2))

norm của 2 ma trận là :
11.75
11.0


In [79]:
matC= mat1+mat2
matD= mat1-mat2
matE= mat1.dot(mat2)
Etam= mat2.dot(mat1)
print(matC)
print(matD)
print(matE)
print(Etam)

[[ 5 16  8]
 [11  9  7]
 [ 9 13 13]]
[[ 5 -2  8]
 [-7 -9 -7]
 [ 5  1 -5]]
[[ 79 156 121]
 [  0  18   0]
 [ 71 150  85]]
[[ 18   0   0]
 [112 112 100]
 [ 85  77  52]]


In [107]:
#bài 3
vec1=np.linspace(0, 100, 21)


In [110]:
u,v,w=np.split(vec1,3)
np.split(vec1,3)

[array([ 0.,  5., 10., 15., 20., 25., 30.]),
 array([35., 40., 45., 50., 55., 60., 65.]),
 array([ 70.,  75.,  80.,  85.,  90.,  95., 100.])]

In [100]:
u*v

array([   0.,  200.,  450.,  750., 1100., 1500., 1950.])

In [101]:
v.dot(w)

30450.0

In [103]:
np.shape(u)

(7,)

In [104]:
u.transpose()

array([ 0.,  5., 10., 15., 20., 25., 30.])

In [105]:
np.shape(u)

(7,)

In [ ]:
#chuyển vị như nhau vì vector chỉ có 1 chiều
