# Đề thi Giữa kỳ Đại số tuyến tính cho Khoa học dữ liệu
## Khoa CNTT - trường ĐH Công nghiệp.
### Nhóm thực hành 1 & 2. Ngày 01/04/2022. Thời gian làm bài: 15h30' - 17h15'.

In [1]:
import numpy as np
from scipy import linalg
from sympy import *

## Bài 1. (4 điểm)
Cho hai ma trận sau đây

# MSSV : 20116351

$$A=\left( \begin{matrix}
   1 & 0 & 2 & a  \\
   1 & 2 & 4 & b  \\
   -1 & 2 & 0 & c  \\
   3 & -1 & 3 & d  \\
\end{matrix} \right), B=\left( \begin{matrix}
   4 & 5 & 1 & -2  \\
   0 & 1 & 2 & 1  \\
   0 & -2 & -3 & 1  \\
   a & b & c & d  \\
\end{matrix} \right)$$
trong đó $a,b,c,d$ là $4$ số cuối trong $MSSV$ (viết theo thứ tự từ trái sang phải). Khi làm bài, $SV$ chủ động thay các mã số đó vào đề bài trên.

Bằng cách dùng các thư viện có hỗ trợ sẵn của Python, hãy thực hiện các yêu cầu sau:
* a) Tính $B+A$, $B{{A}^{T}}$, $2A-3B$.
* b) Tính $\det (A)$ , $\det ({{B}^{T}}+2I)$, $rank(AB).$ 
* c) Tính norm của vector hàng $1$ của $A,$ tính norm của vector cột $3$ của $B,$ tính tổng các phần tử trên đường chéo của $A.$
* d) Kiểm tra công thức ${{(AB)}^{T}}={{B}^{T}}{{A}^{T}}$ dựa trên hai ma trận đã cho.
* e) Kiểm tra công thức $det(AB) = det(A)det(B)$ dựa trên hai ma trận đã cho.
* f) Sinh ngẫu nhiên một ma trận $C$ có kích thước $4\times 4$ với các phần tử là số nguyên trong miền từ $-9\to 9$, từ đó in ra các phần tử nằm phía dưới đường chéo của $A+BC.$ 

*Bài Làm*

In [2]:
A=np.array([[1,0,2,6],
            [1,2,4,3],
            [-1,2,0,5],
            [3,-1,3,1]])
B=np.array([[4,5,1,-2],
            [0,1,2,1],
            [0,-2,-3,1],
            [6,3,5,1]])

**Câu a) Tính $B+A$, $B{{A}^{T}}$, $2A-3B$.**

In [3]:
pl=B+A
print('A+B là: \n',pl)

A+B là: 
 [[ 5  5  3  4]
 [ 1  3  6  4]
 [-1  0 -3  6]
 [ 9  2  8  2]]


In [4]:
mul=B@A.T
print('B dot A.Transpose là :\n',mul)

B dot A.Transpose là :
 [[ -6  12  -4   8]
 [ 10  13   7   6]
 [  0 -13   1  -6]
 [ 22  35   5  31]]


In [5]:
singAB=2*A-3*B
print('2A-3B là:\n',singAB)

2A-3B là:
 [[-10 -15   1  18]
 [  2   1   2   3]
 [ -2  10   9   7]
 [-12 -11  -9  -1]]


**b) Tính $\det (A)$ , $\det ({{B}^{T}}+2I)$, $rank(AB).$**

In [6]:
detA=linalg.det(A)
print('det(A) =',round(detA,4))

det(A) = 56.0


In [7]:
det_B_2I = linalg.det(B.T+2*np.identity(4))
print('det(B.T + 2I)=',det_B_2I)

det(B.T + 2I)= -126.0


In [8]:
mulAB=A@B
rank_AB=np.linalg.matrix_rank(mulAB)
print('Rank của AB là:',rank_AB)

Rank của AB là: 4


**c) Tính norm của vector hàng $1$ của $A,$ tính norm của vector cột $3$ của $B,$ tính tổng các phần tử trên đường chéo của $A.$**

In [9]:
norm_A=linalg.norm(A[0])
print('Độ dài của vector hàng 1 của A là:',round(norm_A,4))

Độ dài của vector hàng 1 của A là: 6.4031


In [10]:
norm_b=linalg.norm(B[:,2])
print('Độ dài của vector cột 3 của B là:',round(norm_b,4))

Độ dài của vector cột 3 của B là: 6.245


In [11]:
traceA=np.trace(A)
print('Tổng các phần tử trên đường chéo của A =',traceA)

Tổng các phần tử trên đường chéo của A = 4


 **d) Kiểm tra công thức ${{(AB)}^{T}}={{B}^{T}}{{A}^{T}}$ dựa trên hai ma trận đã cho.**

In [12]:
mat1=mulAB.T
mat1

array([[40, 22, 26, 18],
       [19,  8, 12, 11],
       [25,  8, 28, -3],
       [ 6,  7,  9, -3]])

In [13]:
mat2=B.T@A.T
mat2

array([[40, 22, 26, 18],
       [19,  8, 12, 11],
       [25,  8, 28, -3],
       [ 6,  7,  9, -3]])

In [14]:
np.allclose(mat1,mat2)

True

*Ta thấy mat1 = mat2*

**e) Kiểm tra công thức $det(AB) = det(A)det(B)$ dựa trên hai ma trận đã cho.**

In [15]:
det_AB=linalg.det(mulAB)
det_AB

-6495.999999999993

In [16]:
detA_B = linalg.det(A)*linalg.det(B)
detA_B

-6496.000000000004

Ta thấy $det(AB) \approx det(A)det(B)$

**f) Sinh ngẫu nhiên một ma trận $C$ có kích thước $4\times 4$ với các phần tử là số nguyên trong miền từ $-9\to 9$, từ đó in ra các phần tử nằm phía dưới đường chéo của $A+BC.$**

In [17]:
C= np.random.randint(-9,9,size=(4,4))
C

array([[-7, -3, -5,  1],
       [-7,  7, -6, -8],
       [-2,  5, -1,  8],
       [ 6,  1, -9,  0]])

In [18]:
A_BC= A+B@C
tril_A_BC=np.tril(A_BC)
print('Các phần từ nằm dưới đường chéo chính của A+BC là:\n',tril_A_BC)

Các phần từ nằm dưới đường chéo chính của A+BC là:
 [[-76   0   0   0]
 [ -4  20   0   0]
 [ 25 -26   6   0]
 [-64  28 -59  23]]


## Bài 2. (2 điểm)
Kết quả học tập của một nhóm sinh viên ở môn Đại số tuyến tính cho Khoa học dữ liệu được cho trong bảng bên dưới. Sinh viên chỉ qua môn nếu điểm tổng kết không dưới $5.0$.

|Sinh viên | BT cá nhân  | Báo cáo   | Giữa kỳ   | Cuối kỳ   |
|----------|-------------|-----------|-----------|-----------|
|  A       |     8       |    7      |    6      |    4      |
|  B       |     0       |    7      |    5      |    6      |
|  C       |     3       |    9      |    4      |    5      |
|  D       |     7       |    8      |    3      |    5      |
|  E       |     10      |    10     |    10     |    9      |
|  F       |     6       |    0      |    6      |    5      |

Giảng viên đang cân nhắc cho các điểm theo trọng số nào để có lợi cho các sinh viên nhất (ít người rớt nhất), có $3$ phương án:
* $0.2, 0.2, 0.2, 0.4$.
* $0.1, 0.1, 0.3, 0.5.$
* $0.1, 0.2, 0.3, 0.4.$

Hãy giúp giảng viên lựa chọn phương án thích hợp.

**Bài làm:**

In [19]:
student=np.array([[8,7,6,4],
                 [0,7,5,6],
                 [3,9,4,5],
                 [7,8,3,5],
                 [10,10,10,9],
                 [6,0,6,5]])
ts1=np.array([[0.2,0.2,0.2,0.4]]).reshape(4,-1)
ts2=np.array([[0.1,0.1,0.3,0.5]]).reshape(4,-1)
ts3=np.array([[0.1,0.2,0.3,0.4]]).reshape(4,-1)

In [20]:
score1=student@ts1
score2=student@ts2
score3=student@ts3
print('score1:\n',score1,'\n score2:\n',score2,'\n score3:\n',score3)

score1:
 [[5.8]
 [4.8]
 [5.2]
 [5.6]
 [9.6]
 [4.4]] 
 score2:
 [[5.3]
 [5.2]
 [4.9]
 [4.9]
 [9.5]
 [4.9]] 
 score3:
 [[5.6]
 [5.3]
 [5.3]
 [5.2]
 [9.6]
 [4.4]]


In [21]:
sv_pass1=(np.select([score1 >=5.0, score1 < 5.0],['p', 'f']) == "p").sum()
sv_pass2=(np.select([score2 >=5.0, score2 < 5.0],['p', 'f']) == "p").sum()
sv_pass3=(np.select([score3 >=5.0, score3 < 5.0],['p', 'f']) == "p").sum()
print('Số lượng sinh viên pass khi cho điểm theo ts1 là:',sv_pass1)
print('Số lượng sinh viên pass khi cho điểm theo ts2 là:',sv_pass2)
print('Số lượng sinh viên pass khi cho điểm theo ts3 là:',sv_pass3)

Số lượng sinh viên pass khi cho điểm theo ts1 là: 4
Số lượng sinh viên pass khi cho điểm theo ts2 là: 3
Số lượng sinh viên pass khi cho điểm theo ts3 là: 5


* Vậy giảng viên cho điểm theo trọng số thứ 3 sẽ có lợi cho sinh viên nhất

## Bài 3. (2  điểm)
Cho bài toán sau, hãy bằng cách lập hệ phương trình thích hợp và giải bằng Python theo **ít nhất $2$ cách khác nhau**: <br>

Trong đợt dịch cúm Covid-19, sinh viên của một trường Đại học có nhận được trợ cấp từ nhà trường, từ địa phương và từ hội cựu sinh viên. Khảo sát trong một lớp học có ba nhóm: đang ở quê, đang ở trọ tại TPHCM và đang ở KTX trường. Biết rằng mức tiền hỗ trợ tiền:
* Của trường cho các nhóm trên lần lượt là: $200k, 600k, 400k$; 
* Của địa phương là: $500k, 500k, 500k$; 
* Của hội cựu sinh viên là: $0k, 700k, 300k.$

Biết rằng tổng tiền mà sinh viên được từ nhà trường là $37$ triệu, từ địa phương là $50$ triệu và từ hội cựu sinh viên là $29$ triệu. Tính tổng sinh viên của lớp.

**Bài làm:**

Ta có HPT: $\left\{\begin{matrix}
200x &+600y  &+400z  &=37000 \\ 
 500x&  +500y&  +500z& =50000 \\ 
 & 700y & +300z & =29000
\end{matrix}\right.$

Cách 1: giải bằng công thức : $x=A^{-1}b$

In [22]:
A=np.array([[200,600,400],
            [500,500,500],
            [0,700,300]])
b=np.array([[37000,50000,29000]]).reshape(3,-1)
x=linalg.inv(A)@b
x

array([[50.],
       [35.],
       [15.]])

In [23]:
print('Tổng số sinh viên của lớp là',round(x.sum(),3))

Tổng số sinh viên của lớp là 100.0


Cách 2: giải bằng hàm solve của scipy 

In [24]:
x= linalg.solve(A,b)
x

array([[50.],
       [35.],
       [15.]])

In [25]:
print('Tổng số sinh viên của lớp là',round(x.sum(),3))

Tổng số sinh viên của lớp là 100.0


Cách 3: giải bằng thư viện Sympy

In [26]:
x=Symbol('x')
y=Symbol('y')
z=Symbol('z')
kq=solve([200*x+600*y+400*z-37000, 500*x+500*y+500*z-50000, 0*x+700*y+300*z-29000],[x,y,z])
kq

{x: 50, y: 35, z: 15}

In [27]:
print('Tổng số sinh viên của lớp là:',kq[x]+kq[y]+kq[z])

Tổng số sinh viên của lớp là: 100


## Bài 4. (2 điểm)
Cho ma trận: $M=\left( \begin{matrix}
   2 & a & -2  \\
   0 & 3 & 0  \\
   0 & 0 & 3  \\
\end{matrix} \right)$ trong đó $a$ là tham số thực.
* a) Cho $a=1,$ hãy chéo hóa ma trận này để thu được ma trận $D$ bằng cách dùng thư viện của Python và kiểm chứng lại bằng việc tính toán từng bước để tìm đa thức đặc trưng và các giá trị riêng của $M$. Từ đó hãy nêu cách tính ${{M}^{99}}$.
* b) Ma trận chéo hóa $D$ của $M$ luôn không đổi với mọi giá trị $a$ tùy ý, hãy kiểm chứng với vài giá trị cụ thể của $a$ và giải thích lý do.


**Bài làm**

Câu a) Cho $a=1,$ hãy chéo hóa ma trận này để thu được ma trận $D$ bằng cách dùng thư viện của Python và kiểm chứng lại bằng việc tính toán từng bước để tìm đa thức đặc trưng và các giá trị riêng của $M$. Từ đó hãy nêu cách tính ${{M}^{99}}$.

In [28]:
M= Matrix([[2,1,-2],
           [0,3,0],
           [0,0,3]])
I = np.identity(3)
P,D = M.diagonalize()
D

Matrix([
[2, 0, 0],
[0, 3, 0],
[0, 0, 3]])

Tìm phương trình đặc trưng và trị riêng

In [29]:
x=Symbol('x')
det(M-x*I)

-1.0*x**3 + 8.0*x**2 - 21.0*x + 18

Vậy phương trình đặc trưng là:$\displaystyle - 1.0 x^{3} + 8.0 x^{2} - 21.0 x + 18$

In [30]:
f=solve([det(M-x*I)],[x])
f

[(2.00000000000000,), (3.00000000000000,)]

Vậy ta có 2 trị riêng là $$\lambda_1 =2, \lambda_2=3$$

Để tính $M^{99}$: <BR>
Ta lấy: $$M=PDP^{-1}\rightarrow M^{99}=PD^{99}P^{-1}$$ <br>


Câu b) Ma trận chéo hóa $D$ của $M$ luôn không đổi với mọi giá trị $a$ tùy ý, hãy kiểm chứng với vài giá trị cụ thể của $a$ và giải thích lý do.

In [31]:
import random

In [32]:
a=random.randint(0,9)
print('a =',a)
N= Matrix([[2,a,-2],
           [0,3,0],
           [0,0,3]])
P,D=N.diagonalize()
D

a = 3


Matrix([
[2, 0, 0],
[0, 3, 0],
[0, 0, 3]])

Vì M là ma trận tam giác trên nên khi chéo hóa D sẽ bằng các phần tử trên đường chéo chính 